# Generated by Django 3.2.5 on 2021-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accapp', '0002_auto_20211123_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
