# Generated by Django 3.2.5 on 2021-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='birth_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='address',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='myuser',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
